apiVersion: v1
kind: Service
metadata:
  name: hot-doks-app-service
  labels:
    app: hot-doks-app
spec:
  type: LoadBalancer  # Use ClusterIP for internal apps
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: hot-doks-app