server:
  port: 8080
  servlet:
    context-path: /hot-doks-api

spring:
  application:
    name: hot-doks-api
  
  # Database Configuration
  datasource:
    url: jdbc:postgresql://localhost:5432/hotdoks
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        enable_lazy_load_no_trans: true
        # Disable automatic schema generation/update
        ddl-auto: none
    open-in-view: false

# Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# OpenAPI/Swagger Configuration
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
